### ISSUE TITLE
Question: limit selection

### ISSUE THREAD

**Issue by kimilau** [lou/multi-select#127]
Is it possible to limit the selection to eight entries.

**Comment by alanning** [comment]
I put together an example that limits the selection count:  http://jsfiddle.net/Luybq3sx/

It does not handle the case where your select element already has items selected but you can add that in.

Dependencies: jQuery, underscore, loudev.multiselect

Here's the source:

*HTML*
```
<body>
    <select id="networks" multiple="multiple">
        <option value="elem1">Elem 1</option>
        <option value="elem2">Elem 2</option>
        <option value="elem3">Elem 3</option>
        <option value="elem4">Elem 4</option>
        <option value="elem5">Elem 5</option>
        <option value="elem6">Elem 6</option>
        <option value="elem7">Elem 7</option>
    </select>
    
    <textarea id="log"></textarea>
</body>
```


*JAVASCRIPT*
```
var MAX_SELECTABLE_OPTIONS = 3,
    selectedCount = 0

$('#networks').multiSelect({
  afterSelect: afterSelect,
  afterDeselect: afterDeselect
})

function afterSelect (values) {
  if (values) {
    selectedCount += values.length
  }
  updateMultiSelect(selectedCount)
}

function afterDeselect (values) {
  if (values) {
    selectedCount -= values.length
  }
  updateMultiSelect(selectedCount)
}

function updateMultiSelect(selectedCount) {
  var $networks = $('#networks'),
      selectedValues = $networks.val()

  if (selectedCount >= MAX_SELECTABLE_OPTIONS) {
    $networks.children().each(function () {
      if (!_.contains(selectedValues, this.value)) {
        log('disabling', this.value)
        $(this).attr('disabled', 'disabled')
      }
    })
  } else {
    $networks.children().removeAttr('disabled')
  }

  $networks.multiSelect('refresh')

  log('[updateMultiSelect] selectedCount', selectedCount)
}  // end updateMultiSelect

function log () {
  var $log = $('#log'),
      args = Array.prototype.slice.call(arguments)

  $log.text($log.text() + args.join(' ') + "\n")
}
```

**Comment by emailopened** [comment]
Hello
I am looking to use this adjustment to limit selection of categories to 4 and it works perfectly if I dont use optgroup but if I include the optgroup, the $networks.children().each( scrolls through the optgroups and not the options? Do you have a suggestion for how to adjust this if we are using optgroups?

Your time is much appreciated. 
Thank you.
Keith

**Comment by alanning** [comment]
Perhaps `$networks.children().children().each()`?

**Comment by emailopened** [comment]
Hey there . that was exactly what it needed. That is awesome.

Thank you for the super fast response.

**Comment by christianmagill** [comment]
I've expanded on the above example to:

- take initial state into consideration
- load limit setting via data attribute
- keep logic encapsulated on a per element basis, so you can have multiple
- stop refreshing the element for better compatibility with other solutions

The example also incorporates jQuery UI Sortable and Quicksearch.

https://gist.github.com/christianmagill/a43772878df798830d0b

**Comment by teej043** [comment]
Just to save that extra kb, I tried using jquery `$.contains( selectedValues, this.value );` rather than the underscore, it seemed to worked.

**Comment by Faisal-nfl** [comment]
its causing issues when that.selectLimit = 0 at start

**Comment by web-masta** [comment]
> I put together an example that limits the selection count: http://jsfiddle.net/Luybq3sx/

I've made my own version for limiting. It's much shorter:

```
var networks = $('#networks')
var limit = 3
networks.multiSelect()
networks.change(function() {
  if ($(this).val().length >= limit) {
    $(this).find(':not(:selected)').prop('disabled', true)
    networks.multiSelect('refresh')
  } else {
    $(this).find(':not(:selected)').prop('disabled', false)
    networks.multiSelect('refresh')
  }
});
```


Live demo - http://jsfiddle.net/y2g3hpaw/2/
