### ISSUE TITLE
Change the order of selected items

### ISSUE THREAD

**Issue by bostondevin** [lou/multi-select#148]
Can you make it so we can change the order of the selected items? Maybe by dragging them up and down or by buttons?

**Comment by SimonEast** [comment]
I was looking for this functionality too.  For anyone else wondering, there are some other similar projects that contain drag-drop reordering functionality:

https://github.com/vicb/bsmSelect ([see demo](http://www.suumit.com/projects/bsmSelect/examples/index.html))
http://joevanderjagt.com/better-multiple-select-with-sorting/
https://github.com/mateagar/fieldChooser
