### ISSUE TITLE
Deselect_all 

### ISSUE THREAD

**Issue by rmoulliet** [lou/multi-select#174]
When I do $('#category_ids').multiSelect('deselect_all'), I get this error:

 Uncaught Error: Syntax error, unrecognized expression: #category_ids option[value=27,46]

What I believe is happening is the function is trying to deselect all at once rather than cycling through, which causes an issue with my deselect function. 

![image](https://cloud.githubusercontent.com/assets/10349960/5579382/51f4ea86-8fff-11e4-8390-4792e632a6bf.png)

![image](https://cloud.githubusercontent.com/assets/10349960/5579390/6f2da426-8fff-11e4-901d-d32f56091fa9.png)

Of course a quick fix is to cycle through the values returned. I think it would be better if it was considered if there is a deselect function by the user.

**Comment by chrisvoo** [comment]
I cannot understand why you have to use ```attr('selected')```. ```deselect_all``` calls only once ```afterDeselect```, you're right, but I cannot see the need to update the element.

**Comment by lou** [comment]
Unfortunately cycling through all items would be a terrible idea on big select (500+ items) because it would be very slow.
As @chrisvoo said I do not understand what you are trying to achieve with your callbacks.

Please feel free to re-open the issue if needed.
