### ISSUE TITLE
Issue while implementing with Angularjs

### ISSUE THREAD

**Issue by ppusapati** [lou/multi-select#175]
It doesn't work when implementing with Angularjs

**Comment by gauravjhs** [comment]
I have used it with angularjs and its working properly. If you can elaborate then may be i can help you out.

**Comment by targetoyes** [comment]
I have the same problem.
<select multiple="multiple" id="public-select" ng-options="i for i in xxx">
</select>
or
<select multiple="multiple" id="public-select">
    <option ng-repeat="i for i in xxx" value='i'>((i))</option>
</select>
all not work

**Comment by gauravjhs** [comment]
You need to create a directive and initialize the select box "element.multiSelect({})" from there.

**Comment by CicciMTS** [comment]
I can't figure out, someone resolve the issue?

**Comment by gauravjhs** [comment]
Please explain your issue or create a jsbin

**Comment by CicciMTS** [comment]
The issue is the same of @ppusapati . I tried to create a directive to initialize the multiSelect as you suggest, but doesn't works.
The only way to work is write static option in select, but is useless in this way.

**Comment by gauravjhs** [comment]
try putting element.multiSelect({}) in a $timout

**Comment by CicciMTS** [comment]
Great! In this way initialization works. But have you any idea how can selected some items on page load? Just putting the selected elements in array of ngModel seems doesn't works.

**Comment by lou** [comment]
I do not use Angular so I can not help, but this issue seems to be resolved.
Feel free to re-open it if it's not the case.

**Comment by rqx110** [comment]
@gauravjhs could you share your code?

**Comment by gauravjhs** [comment]
<code>
app.directive('customMultiSelect', ["$timeout", function($timeout) {
    return {
    restrict: 'A', 
    link: function(scope, element, attrs, tabsCtrl) {
    	scope.$watch('selectedValues',function(selectedValues){
    		$timeout(function() {
    			element.val(scope.selectedValues);
        		element.multiSelect({});
        	},0);
		},true);
        element.on('$destroy', function() {
        	element.multiSelect('destroy');
        });
    }
   };
}]);
</code>

**Comment by jibusayone** [comment]
@CicciMTS Can you share your code? I would like to see both the initialization, and the pre-selected items on page load part.

**Comment by rqx110** [comment]
@gauravjhs hwo to use your code? what's your html code

**Comment by gauravjhs** [comment]
Just mark your html code("<select custom-multi-select></select>") with directive custom-multi-select and use above code for directive

**Comment by EtienneR** [comment]
Hi, I'am not an Angular directives expert but I found a (dirty) solution.

In your controller
```javascript
$scope.selectedValues = {
  'available': ['a', 'b'],
  'selected': ['c', 'd'],
};

$scope.save = function () {
  var result = [];
  $('#mySelect :selected').each(function(i, selected){
    result[i] = $(selected).text();
  });
  console.log(result);
};
```

Then in the directive

```javascript
app.directive('multiselectView', function ($timeout) { 
  return { 
    restrict: "E",
    template:
    '<select multiple >' +
    '<option ng-repeat="item in selectedValues.available" value="{{item}}">{{item}}</option>' +
    '<option ng-repeat="item in selectedValues.selected" value="{{item}}" selected>{{item}}</option>' +
    '</select>',
    link: function ($scope, element, attrs) {
      var el = $('#' + attrs.id);
      $scope.$watch('selectedValues', function (selectedValues) {
        $timeout(function() {
          el.val(selectedValues);
          el.multiSelect({});
        },0); 
      },true);
    }
  }; 
});
```

Wich does a component in the view (inside the controller) like 
```html
<multiselect-view id="mySelect"></multiselect-view>
<button ng-click="save()">Save</button>
```
