### ISSUE TITLE
.ms-container prevents resizing.

### ISSUE THREAD

**Issue by roaringskyinc** [lou/multi-select#178]
The 45% width of <code>.ms-selectable</code> and <code>.ms-selection</code>  is prevented from spanning any container wider than 370px by the <code>.ms-container</code> width of 370px in multi-select.css line 1.

**Comment by rzlxl** [comment]
I think you can try put   <code>width: 100%;</code> at .ms-container

**Comment by lou** [comment]
Maybe you should see the CSS  file included in this plugin as an example.
You can customize the CSS to fit to your project.

But I definitely will dig into the CSS so it will be more flexible.

**Comment by Abdulmanan0315** [comment]
set `width:auto;` it will resize according to the parent
