### ISSUE TITLE
Skip prompt or empty value from selection box

### ISSUE THREAD

**Issue by adiramardiani** [lou/multi-select#191]
I use prompt or empty value like :
```html
<select id="" name="User[role_list]">
     <option value="">Choose a Role</option>
     <option value="1">Value 1</option>
</select>
```

How to exclude this from selection box ?
![role](https://cloud.githubusercontent.com/assets/8703419/8328352/4e37d022-1a9a-11e5-9646-10012059be22.png)

**Comment by lou** [comment]
Hi @adiramardiani,
The plugin has no way to handle the prompt thing.
I do not understand what behavior do you expect? 

You could you simply remove the `<option value="">Choose a Role</option>` from your original select?
