### ISSUE TITLE
'ms-hover' class leaking out of multiselect code?

### ISSUE THREAD

**Issue by EML-github** [lou/multi-select#192]
Anyone seen this? I have a site which includes a multiselect (0.9.11) and a completely unrelated `contenteditable` div. This `<div>` is in a class hierarchy where the class names are all prefixed `note-` (it's a WYSIWYG text editor; see summernote.org). There is no `<select>` anywhere in the hierarchy.

The issue is that the multiselect code is adding a class of `ms-hover` to list items in an `<ul>` in this div. It doesn't cause a problem, but it's obviously not desirable. Presumably there's a problem with the multiselect code that adds the `ms-hover` class, but I haven't looked at it in detail.

**Comment by lou** [comment]
This should be fixed with my last commit https://github.com/lou/multi-select/commit/5bd126d1f7e01faa41401e7bb88641f3575900d7
Thank you @EML-github for the report
