### ISSUE TITLE
Very slow when over a thousand elements

### ISSUE THREAD

**Issue by alimovz** [lou/multi-select#196]
The scrolling/highlighting/selecting of the elements gets pretty slow when there a a lot of elements in the list. In my case there are about 1000 elements and when you mouse over an element, it takes about a second to highlight it. What would be the best way for me to speed it up?

**Comment by ChauskinRodion** [comment]
Have same question. Firefox 40.0.3 show me "A script running on this page may be busy" message and it makes me sad :(
In my case there are ~5k elements in list.

**Comment by lou** [comment]
@alimovz my last commit https://github.com/lou/multi-select/commit/5bd126d1f7e01faa41401e7bb88641f3575900d7 should fix your issue.

@ChauskinRodion unfortunately I did not think this plugin to have more than 1K elements.
 I'm sorry for that one, but you will have to wait until I take the time to think and refactor the entire plugin.

**Comment by alimovz** [comment]
Great stuff. Thank you.

**Comment by ChauskinRodion** [comment]
Ok. Thanks for explanation. thank you.
btw, we resolved issue using async preloader data from server to list when user start typing  :smile:
