### ISSUE TITLE
Can you Limit # of Selected Items?

### ISSUE THREAD

**Issue by hgcsm** [lou/multi-select#197]
I'm trying to limit the # of selected items to 2.  Essentially a form to pick a Primary Person and Secondary person from a full list.

Thanks for any tips.

I don't have the skills to contribute much but I figured out a nifty "hack" to make the left list have "opt-group" while the right will maintain order.  Simply style the "disabled" option to look like an opt group header.  As you select, you will lose the opt group, but it makes the left side more user-friendly at least.

Thanks!
Robert

**Comment by validuz** [comment]
Had a similar need.  This is what I did.  NOt an answer to your question, but maybe a start.
$("#frontColors").change(function(){
	var fcolors = $(this).val().length;
	if (fcolors>3) alert('only 3 are recommended');
});

You've asked a good question.  Let me know if you find an answer.

V

**Comment by lou** [comment]
Maybe this can help https://github.com/lou/multi-select/issues/127#issuecomment-73767233
