### ISSUE TITLE
How to get id of all options on right panel 

### ISSUE THREAD

**Issue by arth1992** [lou/multi-select#199]
After selecting all the data from the left list i do a ajax call and i want to get id of all the options on the left, but i saw the elements are all in ul , li format so there is no function to get result data

**Comment by lou** [comment]
Do you really need the list of ID or the VALUES of the selected items?
This plugin is a drop-in replacement of the standard select with the multiple option activated.
It means that you can use the standard methods on your element.
`$('#your-select').val();` will return an array of all the selected values.

Feel free to re-open this issue if it does not solve your problem.

**Comment by luisgurmendez** [comment]
And what id my options has extra data? How would i get this values?

**Comment by lou** [comment]
You could do something like this: `$('#your-select .ms-selection li.ms-elem-selection')`

**Comment by luisgurmendez** [comment]
Already try but nothing :(
I also try  $('#your-select .ms-selection li.ms-selected')
 thanks for the help anyway :)
I made a javascript object that stores values and keys to solve this, i know its not the best solution but i was kind of in a hurry

**Comment by luisgurmendez** [comment]
This is weird...
>$('#myselect .ms-selection')
--> []
