### ISSUE TITLE
Multi Select not being initialized

### ISSUE THREAD

**Issue by kirtesh08** [lou/multi-select#200]
`<div id="PageList" class="portlet-body fuelux" >
                <select name="Pages[]" size="20" id="Pages" multiple="multiple" style="border:none;width:100%">
                <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                    <option>xyz</option>
                        <option>xyz</option>
                </select>
            </div>`

   `<script src="~/assets/plugins/jquery-1.10.1.min.js"></script>`
  ` <script src="~/assets/scripts/ui-jqueryui.js"></script>`

`<script src="~/assets/lou-multi-select-759348a/js/jquery.multi-select.js" type="text/javascript"></script>`
`<script>`

   ` $(document).ready(function () {`
        `$('#Pages').multiSelect();`
`});`
`</script>`

I have done something like this and console gives me Error: Uncaught TypeError: $(...).multiSelect is not a function

**Comment by lou** [comment]
@kirtesh08 I think that you have an issue with your stack but not the multiselect plugin itself.
Maybe the path to the multiselect javascript file is not good.
Did you manage to resolve it ?
