### ISSUE TITLE
Small issue with CSS styling capability

### ISSUE THREAD

**Issue by jsh562** [lou/multi-select#204]
Trying to style the elements for positioning and sizing.

I am able to change the size and position but this image still stays in the same location:
![image](https://cloud.githubusercontent.com/assets/6527366/11254568/4b9bb296-8df6-11e5-9c29-d7c942499637.png)
And I can't find any references to this image in the html... =(

**Comment by lou** [comment]
Hi @jsh562 
This image is displayed thanks to CSS.
https://github.com/lou/multi-select/blob/master/css/multi-select.css#L2

**Comment by jsh562** [comment]
@lou
Thank you!
