### ISSUE TITLE
Ability to initialise option items selected 

### ISSUE THREAD

**Issue by peterbrennen** [lou/multi-select#235]
I wanted to reflect settings in the DB when the page was loaded but could not find a way to add an option as selected. I have modified my local file thus:
```
    'addOption' : function(options){
      var that = this;

      if (options.value !== undefined && options.value !== null){
        options = [options];
      } 
      $.each(options, function(index, option){
        if (option.value !== undefined && option.value !== null &&
            that.$element.find("option[value='"+option.value+"']").length === 0){
          var $option = $('<option value="'+option.value+'">'+option.text+'</option>'),
              index = parseInt((typeof option.index === 'undefined' ? that.$element.children().length : option.index)),
              $container = option.nested === undefined ? that.$element : $("optgroup[label='"+option.nested+"']");

          // PB: 23-06-2016:  If marked as selected from start, reset template
          if (option.selected != undefined)
              $option = $('<option value="' + option.value + '" selected>' + option.text + '</option>')

          $option.insertAt(index, $container);
          that.generateLisFromOption($option.get(0), index, option.nested);
        }
      });
    },

```

**Comment by jessmitch42** [comment]
I updated my code to include this because I also need a way to have some 'addOption' options be preset to 'selected'. The options show as 'selected' in the DOM but they aren't being generated on the 'selected' div in the multiselect. Everything is still showing up on the selectable side regardless of some of the options having the selected attribute and some not. 

Any thoughts? Did this fix work for you?

**Comment by peterbrennen** [comment]
Hey Jess, yes it did work for me. Did you clear your browser cache after the javascript change? If you've got javascript in a PHP file and are using OPCache in Apache (or another caching module), you might need to restart it to get the later file served. Let me know how you get on.

**Comment by jessmitch42** [comment]
Hi Peter. Thanks for the quick response! Glad to know it worked for you. Not sure why it wouldn't work for me too but I'm glad it *should* work at least, haha. I tried clearing cache, restarting, etc. Must be something else.

**Comment by peterbrennen** [comment]
I'll search my code tomorrow to find how I call it.

**Comment by peterbrennen** [comment]
Hey Jess, I replaced this widget in the end with the better searchable tool called **jquery Chosen**, you might have heard of it?  Here is the link:  [https://harvesthq.github.io/chosen/]  Thanks.

**Comment by jessmitch42** [comment]
This is perfect, thanks so much for the link!!!

**Comment by peterbrennen** [comment]
My pleasure :)
