### ISSUE TITLE
First Item Selected and That's It

### ISSUE THREAD

**Issue by ferenczAndras** [lou/multi-select#306]
Hello. I have one selected item. and thats it. Why?

**Comment by Adalsteinnjons** [comment]
Same here, did you find the fix?

**Comment by Emsal92** [comment]
Had the same issue, turns out you can't have the same value on multiple option elements.

**Comment by ognif** [comment]
try console.log($('#myModules').val());

**Comment by Ghostubborn** [comment]
Maybe "multiple" property of "select" element is not set
