### ISSUE TITLE
Support for Bootstrap 4.4

### ISSUE THREAD

**Issue by wilfredswaroop** [lou/multi-select#335]
Can it has support for Bootstrap 4, Because i used it in my project, its not working.

Please help me out.

**Comment by lcapdecomme** [comment]
Hello,
What's the problem ?
I use it on my project with bootstrap 4.4. and everything is ok

**Comment by wilfredswaroop** [comment]
Hello lcapdecomme,
As you said everything is ok with bootstarp 4.4. [The problem which i was faciing was solved].

But, Now can you help me to "Get the selected values from div: ms-selection in the same order i selected.

**Comment by lcapdecomme** [comment]
Hello wilfredswaroop
OK
For the second problem, have you tried: _$("#multiselect").val();_ ?
