### ISSUE TITLE
Can't disable the multi-select after initialisation

### ISSUE THREAD

**Issue by pepijnolivier** [lou/multi-select#62]
I currently want the user to select a maximum of 6 items.
In the afterSelect callback, I retreive the ammount of selected items, and when this number is greater than 5, I want to disable the box.

I do this like so:

[code]
afterSelect: function(value, text){
        var array = $('#multiselect').val();
        if(array.length>5)
            $('#multiselect').attr('disabled','disabled');
        },
[/code]

The disabled attribute is successfully added to the DOM element. However, I can still keep on selecting items.

Is there any other approach I should be following?

**Comment by lordaikins** [comment]
Was trying to achieve a similar stuff and spent time looking for a precise solution. In my case I was parsing an ajax function with remote connection to a php script in the afterSelect and afterDeselect methods. Like this;
[code]
........
	  afterSelect: afterSelect,
	  afterDeselect: afterDeselect
.........
[/code]
So the var _self = this did not work for me.

This however worked, just refreshing the multiselect after calling the disabled attribute.
$('#multiselect').attr('disabled','disabled');
$('#multiselect').multiSelect('refresh');
